### ISSUE TITLE
Support for the new Milight controller

### ISSUE THREAD

**Issue by 2benl** [athombv/com.milight#7] opened 2016-10-27 08:52 UTC
I ordered the new iBox1 controller. Lot's of new Milight products including the possibility to set the saturation and color temperature. 
See: http://futlight.com/productlist.aspx?typeid=100

Will this new controller and the new functions be supported?

**Comment by fvandenreek** [comment] 2016-11-06 19:44
I have the ibox, but I'm still waiting for the lights (gu10 rgb + cct). I can't test if it works, but i can say I can't control the ibox light.
Tell me what you need so perhaps you can make it work. If needed I will share my ibox for research.

**Comment by Gosephe** [comment] 2016-12-16 22:01
Also asking for possibility to control the new iBOX and RGB CCT lights. Homey is just the ONLY solution to connect multiple Mi-Light wifi bridges.

**Comment by RobinBol** [comment] 2017-01-03 14:12
Is this the correct 'iBox' you guys want to have implemented?

http://www.milightwinkel.nl/MILIGHT-WiFi-module-ibox

**Comment by 2benl** [comment] 2017-01-03 14:13
Yep that is the one!

**Comment by RobinBol** [comment] 2017-01-03 14:15
I'll see what I can do, but don't expect it real soon. I think the API is very similar to the one the milight app uses right now, so it is most likely a case of implementing the commands correctly, could (easily) be done by someone from the community!

http://www.limitlessled.com/dev/

**Comment by fvandenreek** [comment] 2017-01-03 19:09
It would be great if some one gave it a shot!

**Comment by Bozo29** [comment] 2017-01-31 06:06
I hope so, i'm also waiting for this.

**Comment by RonniePanken** [comment] 2017-02-03 20:21
Same here, old wifi box is unstable wifi all the time its disconnecting and after reset 1 day its ok but than disconnects again. 
New Ibox is working fine, but no Homey support :(
Would be nice if someone could fix this.

**Comment by fvandenreek** [comment] 2017-02-13 19:09
Looks like there is a bit of action.... to bad it is on openhab [https://github.com/openhab/openhab2-addons/pull/1779](url)

**Comment by TheMrCaveman** [comment] 2017-02-21 14:26
This would be very nice i just got a homey and a bunch of these lights, but they don't work;(

**Comment by RonniePanken** [comment] 2017-02-21 18:22
" RobinBol added the enhancement label 5 days ago"

What does this mean ??

**Comment by RobinBol** [comment] 2017-02-21 19:04
We use that to manage our issues, in general issues labeled bug will get more priority than the ones labeled enhancement for obvious reasons.

**Comment by lunatick84** [comment] 2017-03-03 11:53
+1 for support of the new lights (RGB+CCT) and the iBox2. I have a bunch of these lights, en now they're pretty useless... Thanks!

**Comment by TheMrCaveman** [comment] 2017-03-11 08:28
MM almost half a year and no update yet:(

**Comment by 2benl** [comment] 2017-03-11 09:26
@RobinBol is it possible to raise some funds in advance to see that the ibox gets support? I have literarry no programming skills what so ever. 

The milight app is the second most popular app for lights in the appstore (assuming the order in the appstore is ranked in downloads or views). All the new lights are only controlled by the ibox 1 or 2. 
I for myself just bought 5 new led flutlights 50w rgb cct and can only control them by remote or the Milight app. Turning the garden lights on with Homey would be a great feature. 

@WeeJeWel I think that Milight is one of the most affordable ways to support Home automation lightning at the moment. Full support with Homey might increase sales for both Homey and Milight as controlling smart lightning at home becomes much more affordable.

**Comment by TheMrCaveman** [comment] 2017-03-13 17:10
I have no problem donating for getting this to work with my homey!!!

**Comment by RobinBol** [comment] 2017-03-16 10:19
That is of course a possibility! I am sure there is a community member willing to create an app for the new Milight box, especially if there is some extra incentive;) Try the forum with your proposal!

**Comment by 2benl** [comment] 2017-03-17 07:56
@RobinBol We are trying that now. Nevertheless I think that if Athom itself introduces an app for a brand, they should also maintain the app. In my humble opinion that doesn't only mean fixing bugs, but also supporting new introduced devices (especially when supporting won't take to much time and the api from the supplier is known as you mentioned before). I know your priority is focused on different things than apps at the moment (1.20 etc.). But I think that looking at the community to continue support for an app that Athom introduced isn't the right way. Off course when it happens as with the Fibaro app that is great, but it shouldn't be the first solution. 

And still I see Milight as a great cheap solution for home lightning. The only thing the lack versus HUE are scenes and the option to chose a specific mode (as I think that choosing a specific mode might be possible with the iBox 1 and 2)
I now bought the new floodlights 50 watt for my garden and they are superb.

**Comment by lunatick84** [comment] 2017-03-17 08:57
@2benl I appreciate your work in trying to make a new app. Although I agree that an app created by Athom BV should be maintained by Athom themselves... If the app was initially created by a community member, then it's normal that we cannot demand anything at all. But when the Homey creators themselves promote Homey as working with MiLight and develop an app for it, only to abandon it after a while, that doesn't feel right. How can I trust Athom to keep on updating anything on Homey? The community shouldn't be held responsible for the succes of Athom's hardware. A music/media mode is nice, but the core functionality of the device should be priority. I now have 11 lights in my living room that I need my phone for to switch on/off; while I (incorrectly) thought Homey would be able to control these... Since that basic functionality doesn't work, I'm not really triggered to program complex flows for other stuff, and Homey is just sitting there for now.
I know I'm preaching to the choir here; but maybe someone from Athom will read this... ;)

**Comment by woff3d** [comment] 2017-03-20 08:56
@RobinBol We use Milights floodlights in our tensile architecture systems (see woff.nl) and our customers would like to use Homey to control them, myself included. There is a big market out there. It will definitely boost the success of Homey. I encourage Athom BV to update and add full functionality for this plug-in. 

![w3001 terrasoverkapping westhoff hoofddorp 1](https://cloud.githubusercontent.com/assets/5677505/24093096/6848d75c-0d52-11e7-9120-53674809492b.jpg)

**Comment by RobinBol** [comment] 2017-03-20 15:57
We have received the new Milight controller at our office, we will be looking at creating a driver for this device in the near future!

**Comment by 2benl** [comment] 2017-03-20 16:15
@RobinBol Great news. Would have send you one if I would have known that was what it takes. ;-)

**Comment by priknr1** [comment] 2017-04-04 06:38
@RobinBol 
Will this driver also include the RGB+CCT functionality?
Does near future mean days, weeks or months ✌️

**Comment by priknr1** [comment] 2017-04-10 10:19
@RobinBol  any chance you have a status update for us? :$

**Comment by Gosephe** [comment] 2017-04-14 13:56
Seems to me it's sn abbadon topic. Lake of support is very annoying. Fibaro HC2 also not an option, domotiz or How it's called has support. Have Homey long before release even fibaro switches are not reliable. I do not need a "play" app for homey's feelings, just decent apps like fibaro and mi light control.

**Comment by 2benl** [comment] 2017-04-14 14:00
Nope it is not an abandoned topic. Yesterday @RobinBol wrote in the Milight Forum topic that updating the Milight app is in the top of his to do list. Off course we all want decent apps, but I don't see your post as a motivation for Robin to pick up the Milight app.

**Comment by Gosephe** [comment] 2017-04-14 14:28
4 months ago already asked for an update, strange iam not in the mood for positive feedback??  Just gotchi stuff marked down as making impossible things. I just need basic stuff, reliable. To me that seems impossible (yet). And when it Will happen, hopefully in the near future, all positive credits. Iam sceptic and like more people thinking to buy a HC2 or another Z wave controller. Although Homey has for me the best specs....

**Comment by TheMrCaveman** [comment] 2017-05-21 11:25
So is there any news or progress?

**Comment by RobinBol** [comment] 2017-05-21 18:23
Yes, it is a work in progress

**Comment by RobinBol** [comment] 2017-06-30 15:47
Update: this afternoon I published a beta of the milight app with support for iBox V6! Please let me know if you have feedback.

**Comment by priknr1** [comment] 2017-07-03 12:24
@RobinBol  Does this include rgb+cct functionality? If so, I will buy myself the controller and will start testing, and I might even be able to assist in improving one day

**Comment by RobinBol** [comment] 2017-07-03 12:29
Not sure, Milight is not really consistent in their naming. I think they use rgb+cct interchangeably with RGBWW (which is supported via iBox v6). We don't have any bulbs that are named rgb+cct so I can not test this for you unfortunately. The Milight library we use defines 5 sets of commands; bridge, white, fullcolor, rgb and rgbw. My guess is therefore that rgb+cct uses the fullcolor commands.

So no guarantees, but I think they should work!

**Comment by woff3d** [comment] 2017-07-03 12:39
Thx Robin. I tested some basic functionality, so far so good, more extensive maybe later this week. Unfortunately I'm abroad 2 weeks after. My test environment consists of 2 types of floodlight RGBW and RGB+CCT steered by the iBox1. I had the iBox2, but sold it, so I can't test that now. I'll keep you posted on the results. Tonight some flows become active.

**Comment by Gosephe** [comment] 2017-07-03 13:05
Had Some connecties problems internet. 
BUT Homey Did see 3 iboxes!!! Will test functions this week. So far VERY good!! 

Joost

**Comment by RobinBol** [comment] 2017-07-03 14:00
Great, thanks for testing guys!

**Comment by joostma** [comment] 2017-07-03 14:52
Has been working fine for the past few days with RGG-CCT bulbs with an ibox1!

**Comment by Corbia** [comment] 2017-07-16 14:00
where can I find the beta versie ?

**Comment by priknr1** [comment] 2017-07-17 06:08
In the appstore, it says "View Beta version here" just below the Install button

**Comment by Bozo29** [comment] 2017-07-17 21:05
I'm missing in the beta a flowcard with a slide to combine RGW with CCT (color with warm white/cool white), just like on the remote.
The beta app works great.
Is it possible to change the collor of the lamp off the IBox ?

**Comment by Bozo29** [comment] 2017-07-17 21:12
Is it possible to connect the bulbs with Homey without the IBox like they do with Domotics ?

**Comment by Gosephe** [comment] 2017-07-18 07:40
Nop you need iBox. I can confirm new iBox and coloured CCT lights are working as it should be. 

Iam controlling now 3 iBoxes!!!

**Comment by RobinBol** [comment] 2017-07-18 11:59
@Bozo29 I wasn't aware of such functionality, what does it look like mixing light temperature and color? I don't think we can support that, a bulb has either a color mode, or a white/temperature mode.

**Comment by Bozo29** [comment] 2017-07-19 10:18
@RobinBol 
Exemple:
I have 5 RGB+CCT bulbs, 1 shines on a sidetable. The main color of the sidetable is this time pink. One bulb shines on it with white light and a little bit of pink in it. So I can mix the white light with a color. Now I do it with the remote control (https://ledstrip-specialist.nl/ledstrip-accesoires/RGBWW-RF-Led-lamp-led-strip-afstandsbediening-4-zone. With the saturation control I can mix the white light with RGB).

**Comment by RobinBol** [comment] 2017-07-19 12:52
Ah I see what you mean, saturation. This is indeed missing at the moment, I will put it on my to-do list to add as well!

**Comment by Bozo29** [comment] 2017-07-19 21:36
@RobinBol 
Thanxs

**Comment by Bozo29** [comment] 2017-08-07 06:14
@RobinBol 
Is it possible to control the light on the IBox like they do in the app of Milight ?
I will use that for a warning singel

**Comment by priknr1** [comment] 2017-08-07 06:24
@Bozo29 
I already opened an issue for that: 
https://github.com/athombv/com.milight/issues/13

**Comment by RobinBol** [comment] 2017-08-21 15:08
Closing this issue as support for the iBox has been added and is published in the app store.

**Closed by RobinBol** 2017-08-21 15:08 UTC
Labels: enhancement

**Comment by woff3d** [comment] 2017-08-21 15:11
Thx4all.

Groet, Charles


Met vriendelijke groet | Kind regards
Charles Westhoff






charles@woff.nl <x-msg://60/charles@woff.nl>   | www.woff.nl <http://www.woff.nl/> |  +31 6 3819 4239  
Vliehors 88, 2134XN, Hoofddorp (Nederland)
